config/routes.rb
Rails.application.routes.draw do
  resources :advices
  get 'home/index'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  before_action :set_advice, only: [:show, :edit, :update, :destroy]

  # GET /advices
  # GET /advices.json
  def index
    @advices = Advice.all
  end

  # GET /advices/1
  # GET /advices/1.json
  def show
  end

  # GET /advices/new
  def new
    @advice = Advice.new
  end

  # GET /advices/1/edit
  def edit
  end

  # POST /advices
  # POST /advices.json
  def create
    @advice = Advice.new(advice_params)

    respond_to do |format|
      if @advice.save
        format.html { redirect_to @advice, notice: 'Advice was successfully created.' }
        format.json { render :show, status: :created, location: @advice }
      else
        format.html { render :new }
        format.json { render json: @advice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advices/1
  # PATCH/PUT /advices/1.json
  def update
    respond_to do |format|
      if @advice.update(advice_params)
        format.html { redirect_to @advice, notice: 'Advice was successfully updated.' }
        format.json { render :show, status: :ok, location: @advice }
      else
        format.html { render :edit }
        format.json { render json: @advice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advices/1
  # DELETE /advices/1.json
  def destroy
    @advice.destroy
    respond_to do |format|
      format.html { redirect_to advices_url, notice: 'Advice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advice
      @advice = Advice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advice_params
      params.require(:advice).permit(:name, :description, :time)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render json: {
      status: 'OK',
      results: Advice.select('id, name, description, time'),
      errors: nil
    }, status: 200
  end
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/advices/_form.html.erb
<%= form_with(model: advice, local: true) do |form| %>
  <% if advice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advice.errors.count, "error") %> prohibited this advice from being saved:</h2>

      <ul>
      <% advice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advices/edit.html.erb
<h1>Editing Advice</h1>

<%= render 'form', advice: @advice %>

<%= link_to 'Show', @advice %> |
<%= link_to 'Back', advices_path %>

app/views/advices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advices.each do |advice| %>
      <tr>
        <td><%= advice.name %></td>
        <td><%= advice.description %></td>
        <td><%= advice.time %></td>
        <td><%= link_to 'Show', advice %></td>
        <td><%= link_to 'Edit', edit_advice_path(advice) %></td>
        <td><%= link_to 'Destroy', advice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advice', new_advice_path %>

app/views/advices/new.html.erb
<h1>New Advice</h1>

<%= render 'form', advice: @advice %>

<%= link_to 'Back', advices_path %>

app/views/advices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @advice.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @advice.description %>
</p>

<p>
  <strong>Time:</strong>
  <%= @advice.time %>
</p>

<%= link_to 'Edit', edit_advice_path(@advice) %> |
<%= link_to 'Back', advices_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Party</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>